basePath: /
definitions:
  domain.Error:
    properties:
      message:
        type: string
    type: object
  domain.Geolocation:
    properties:
      city:
        maxLength: 255
        type: string
      country:
        maxLength: 255
        type: string
      country_code:
        type: string
      ip_address:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      mystery_value:
        type: string
    required:
    - city
    - country
    - country_code
    - ip_address
    - latitude
    - longitude
    - mystery_value
    type: object
info:
  contact: {}
  description: Here we handle Geolocation!
  title: Vio Challenge Server
  version: "1.0"
paths:
  /api/v1/geolocations/{ip_address}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ip address
        in: path
        name: ip_address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Geolocation'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.Error'
      summary: Get geolocation by IP address
      tags:
      - geolocation
swagger: "2.0"
